spring:
  datasource:
    url : jdbc:mysql://localhost:3306/microservice
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect
        
    generate-ddl : true
    hibernate:
      ddl:
      auto : update
    show-sql : true
